version: '3.8'
services:
  we-bot-whatsapp:
    image: node-whatsapp-web:1.0
    volumes:
      - ./src:/app/src
      - ./media:/app/media
      - ./index.js:/app/index.js
            - ./node_modules:/app/node_modules  # Montar node_modules
      - ./session:/app/session  # <--- Guarda la sesión aquí
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"